"""Curated Danish topic list for seed-driven SFT generation.

~700 specific topics across ~30 subject areas. Each topic is concrete enough
to prevent Gemini from defaulting to the canonical safe-set (Bohr, Ørsted,
Andersen, hygge, København).

Usage:
    from da_topics import TOPICS_FLAT, sample_topic
    topic = sample_topic(rng)
"""

TOPICS: dict[str, list[str]] = {
    # ── Literature (classic) ────────────────────────────────────────────────
    "literature_classic": [
        "H.C. Andersen og eventyret Fyrtøjet",
        "H.C. Andersen og eventyret Snedronningen",
        "H.C. Andersen og eventyret Skyggen",
        "H.C. Andersen og eventyret Klokken",
        "H.C. Andersens rejser i Italien og Tyskland",
        "Søren Kierkegaard og Enten-Eller",
        "Søren Kierkegaards begreb angst",
        "Søren Kierkegaards pseudonymer",
        "N.F.S. Grundtvig og folkehøjskolen",
        "Grundtvigs salmer",
        "Steen Steensen Blicher og Novellen",
        "B.S. Ingemann og Erik Menveds Barndom",
        "Adam Oehlenschläger og Guldhornene",
        "Johannes Ewald og Kong Christian stod ved højen mast",
        "H.C. Ørsteds bog Aanden i Naturen",
        "Ludvig Holberg og komedien Jeppe på Bjerget",
        "Ludvig Holberg og Erasmus Montanus",
        "Herman Bang og romanen Ved Vejen",
        "J.P. Jacobsen og Niels Lyhne",
        "J.P. Jacobsen og Fru Marie Grubbe",
        "Henrik Pontoppidans Lykke-Per",
        "Karl Gjellerups Nobelpris i 1917",
        "Henrik Pontoppidans Nobelpris i 1917",
        "Johannes V. Jensens Nobelpris i 1944",
        "Johannes V. Jensens Kongens Fald",
        "Johannes V. Jensens Himmerlandshistorier",
        "Karen Blixen og Den afrikanske farm",
        "Karen Blixens Syv Fantastiske Fortællinger",
        "Karen Blixens ophold i Kenya",
        "Martin A. Hansen og Løgneren",
        "Martin Andersen Nexø og Pelle Erobreren",
        "Martin Andersen Nexø og Ditte Menneskebarn",
        "William Heinesens færøske romaner",
        "Tom Kristensens Hærværk",
        "Klaus Rifbjergs Den kroniske uskyld",
        "Ole Lund Kirkegaards Gummi-Tarzan",
        "Astrid Saalbachs teaterstykker",
    ],

    # ── Literature (modern & contemporary) ─────────────────────────────────
    "literature_modern": [
        "Peter Høeg og Frøken Smillas fornemmelse for sne",
        "Jussi Adler-Olsens Afdeling Q-serie",
        "Leif Panduros romaner",
        "Suzanne Brøggers essays",
        "Naja Marie Aidts noveller",
        "Michael Strunges digte",
        "Inger Christensens digtsamling Alfabet",
        "Inger Christensens Sommerfugledalen",
        "Jens Christian Grøndahls romaner",
        "Ida Jessens Hos alfen",
        "Kirsten Hammann og Bannister",
        "Helle Helles minimalisme",
        "Yahya Hassans debutdigtsamling",
        "Olga Ravns Celestine",
        "Josefine Klougarts Om mørke",
        "Dorthe Nors' romaner",
        "Kim Leines Profeterne i Evighedsfjorden",
        "Morten Papes Guds bedste børn",
        "Katrine Marie Guldagers noveller",
    ],

    # ── Film & TV ──────────────────────────────────────────────────────────
    "film_tv": [
        "Lars von Trier og filmen Antichrist",
        "Lars von Trier og filmen Melancholia",
        "Lars von Trier og filmen Dogville",
        "Lars von Trier og filmen Nymphomaniac",
        "Lars von Trier og Dogme 95-bevægelsen",
        "Thomas Vinterberg og Festen (1998)",
        "Thomas Vinterberg og Jagten (2012)",
        "Thomas Vinterberg og Druk (2020) og Oscar-prisen",
        "Bille August og Pelle Erobreren og Guldpalmen",
        "Bille August og Den bedste af alle mødre",
        "Susanne Bier og filmen Hævnen",
        "Susanne Bier og filmen Brødre",
        "Susanne Bier og Efter brylluppet",
        "Nikolaj Arcel og En kongelig affære",
        "Anders Thomas Jensens Adams Æbler",
        "Anders Thomas Jensens De grønne slagtere",
        "Anders Thomas Jensens Retfærdighedens ryttere",
        "Ole Bornedals Nattevagten",
        "Nicolas Winding Refn og Pusher-trilogien",
        "Nicolas Winding Refn og Bronson",
        "Erik Balling og Olsen-banden-filmene",
        "Astrid Henning-Jensens film Palle alene i verden",
        "Gabriel Axel og Babettes Gæstebud",
        "TV-serien Matador",
        "TV-serien Riget af Lars von Trier",
        "TV-serien Forbrydelsen",
        "TV-serien Borgen",
        "TV-serien Broen",
        "TV-serien Rita",
        "TV-serien Krøniken",
        "Filmen Adams æbler",
        "Filmen Blinkende lygter",
        "Filmen Kærlighed ved første hik",
        "Filmen Erik Nietzsche-trilogien",
        "Danske DR-programmer i 1990'erne",
    ],

    # ── Music ──────────────────────────────────────────────────────────────
    "music": [
        "Kim Larsen og bandet Gasolin'",
        "Kim Larsens album Yummi Yummi",
        "Kim Larsen og sangen Kvinde min",
        "Kim Larsen og sangen Papirsklip",
        "Shu-bi-dua og sangen Costa Kalundborg",
        "Shu-bi-dua og Michael Bundesen",
        "TV-2 og forsangeren Steffen Brandt",
        "TV-2 og sangen Bag duggede ruder",
        "Sanne Salomonsens karriere",
        "Rasmus Seebach og hans hits",
        "Lars H.U.G. og bandet Kliché",
        "Aqua og hittet Barbie Girl (1997)",
        "Michael Learns to Rock",
        "Volbeat og forsangeren Michael Poulsen",
        "Volbeats blanding af rock og country",
        "D-A-D (bandet)",
        "Mew og deres postrock-lyd",
        "Whigfield og Saturday Night",
        "Safri Duo",
        "MØ (sangeren Karen Marie Aagaard)",
        "Lukas Grahams sang 7 Years",
        "Medina og hendes danske popkarriere",
        "Nephew og Simon Kvamm",
        "Poul Krebs og sangen Sådan er kærligheden",
        "Anne Linnet og hendes sange",
        "Kim Larsens sang Susan Himmelblå",
        "Kandis og Johnny Hansen",
        "Rikke Thomsen og folkemusikken",
        "Carl Nielsen og symfonien Det uudslukkelige",
        "Carl Nielsen og operaen Maskarade",
        "Rued Langgaards musik",
        "Per Nørgård og hans komponistkarriere",
        "Buster Larsens skuespilkarriere",
    ],

    # ── History (medieval & vikings) ───────────────────────────────────────
    "history_early": [
        "Vikingetidens bosættelser i Jorvik",
        "Vikingernes handel med Byzans",
        "Harald Blåtands konvertering til kristendommen",
        "Jelling-stenene og deres betydning",
        "Vikingeskibene i Roskilde Fjord",
        "Vikingehallen ved Lejre",
        "Ansgar og kristendommens indførelse",
        "Slaget ved Hastings og Harold Godwinsson",
        "Kong Knud den Stores nordsørige",
        "Kong Valdemar den Store og Absalon",
        "Absalon og grundlæggelsen af København",
        "Valdemar Sejr og Jyske Lov",
        "Kalmarunionen (1397)",
        "Dronning Margrete 1.",
        "Slesvig og Holsten i middelalderen",
        "Erik af Pommerns kongegerninger",
        "Christoffer 2. og hans nederlag",
        "Reformationen i Danmark 1536",
        "Hans Tausen og reformationens spredning",
        "Slaget ved Øksnebjerg 1535",
        "Christian 3. og enevældens indførelse",
        "Christian 4. og Trediveårskrigen",
        "Christian 4. og Rundetårn",
        "Christian 4. og Rosenborg Slot",
        "Christian 4. og Frederiksborg Slot",
        "Christian 4. og Kronborg",
        "Enevældens indførelse i 1660",
        "Kongeloven af 1665",
        "Slaget ved Køge Bugt 1677",
        "Peder Griffenfelds fald",
        "Struensee og reformerne under Christian 7.",
        "Struensees henrettelse 1772",
    ],

    # ── History (1800s & modern) ───────────────────────────────────────────
    "history_modern": [
        "Slaget på Reden 1801",
        "Københavns bombardement 1807",
        "Statsbankerotten 1813",
        "Christian 8. og forfatningskampen",
        "Grundloven af 5. juni 1849",
        "Treårskrigen 1848-1850",
        "Krigen i 1864 og tabet af Sønderjylland",
        "Slaget ved Dybbøl 1864",
        "Systemskiftet 1901",
        "Kvinders valgret 1915",
        "Genforeningen 1920",
        "Kanslergadeforliget 1933",
        "Den tyske besættelse 9. april 1940",
        "Frihedsrådet i besættelsestiden",
        "Redningen af de danske jøder i 1943",
        "Christian 10. og hans daglige ridt gennem København",
        "Sabotagegrupperne under besættelsen",
        "BOPA og Holger Danske",
        "Kaj Munk og hans mord i 1944",
        "Marshall-hjælpen efter krigen",
        "Danmarks indtræden i NATO 1949",
        "Danmarks indtræden i EF 1973",
        "Ungdomshuset og BZ-bevægelsen",
        "Nyrup-regeringens økonomiske politik",
        "Muhammed-krisen 2005-2006",
        "Klimatopmødet COP15 i København 2009",
        "Metroens åbning i København 2002",
        "Storebæltsbroen (åbnet 1998)",
        "Øresundsbroen (åbnet 2000)",
    ],

    # ── Royal family ───────────────────────────────────────────────────────
    "royals": [
        "Dronning Margrethe 2.s abdikation i januar 2024",
        "Kong Frederik 10. og Dronning Mary",
        "Prins Henriks liv i Frankrig",
        "Kronprinsesse Marys australske baggrund",
        "Prins Christians udnævnelse til kronprins",
        "Prinsesse Isabellas rolle",
        "Prins Vincent og Prinsesse Josephine",
        "Kongehusets residens Amalienborg",
        "Fredensborg Slot og kongefamiliens ferier",
        "Marselisborg Slot i Aarhus",
        "Dronning Margrethes kunstneriske arbejder",
        "Dronningens nytårstale",
        "Kongelovsændringen om tronfølgen 2009",
        "Grønlandsrejsen med Dannebrog",
        "Prins Joachim og hans familie",
    ],

    # ── Politics & civics ──────────────────────────────────────────────────
    "politics": [
        "Folketingets 179 mandater",
        "De 4 mandater fra Grønland og Færøerne",
        "Statsminister Mette Frederiksen",
        "Lars Løkke Rasmussens tid som statsminister",
        "Anders Fogh Rasmussen og NATO",
        "Poul Nyrup Rasmussens formandskab i Socialdemokratiet",
        "Helle Thorning-Schmidt som første kvindelige statsminister",
        "Uffe Ellemann-Jensens udenrigsministertid",
        "Bertel Haarders lange karriere",
        "Pia Kjærsgaard og grundlæggelsen af Dansk Folkeparti",
        "Villy Søvndal og SF",
        "Enhedslistens dannelse 1989",
        "De Konservatives historiske rolle",
        "Radikale Venstres balance mellem blokkene",
        "Alternativet og Uffe Elbæk",
        "Nye Borgerlige og Pernille Vermund",
        "Moderaterne og Lars Løkke Rasmussen",
        "Grundlovens paragraf 3 (magtens tredeling)",
        "Grundlovens paragraf 77 (ytringsfrihed)",
        "Folketingets Ombudsmand",
        "Statsrevisorerne",
        "Kommunalreformen 2007",
        "Regionsdannelsen 2007",
        "Rigsfællesskabet Danmark-Grønland-Færøerne",
        "Kommunernes selvstyre",
        "Fingerplanen for København",
        "Storkommuner efter 2007",
    ],

    # ── Geography (cities & regions) ───────────────────────────────────────
    "geography_cities": [
        "Aarhus som Danmarks anden største by",
        "Aarhus som Europæisk Kulturhovedstad 2017",
        "Odense og H.C. Andersens by",
        "Aalborg og industriens historie",
        "Esbjerg og fiskeindustrien",
        "Randers og industriens historie",
        "Kolding og Koldinghus",
        "Vejle og Vejle Fjord",
        "Horsens og fængselsmuseet",
        "Silkeborg og søerne",
        "Roskilde og domkirken",
        "Roskilde Festival",
        "Ribe som Danmarks ældste by",
        "Ærøskøbing på Ærø",
        "Skagen og Skagensmalerne",
        "Skagen og Grenen",
        "Bornholm og rundkirkerne",
        "Christiansø og Ertholmene",
        "Læsø og saltsyderiet",
        "Fanø og badestranden",
        "Samsø og vedvarende energi",
        "Møn og Møns Klint",
        "Anholt og fyret",
        "Christiansfeld og Herrnhut-menigheden",
        "Fredericia og fæstningsværkerne",
        "Sønderborg og genforeningen",
        "Tønder og kniplinger",
        "Nyborg og Nyborg Slot",
        "Svendborg og Sydfyn",
        "Frederikssund og vikingespillene",
        "Helsingør og Kronborg",
    ],

    # ── Geography (nature) ─────────────────────────────────────────────────
    "geography_nature": [
        "Vadehavet og verdensarven",
        "Rold Skov som Danmarks største skov",
        "Mols Bjerge nationalpark",
        "Nationalpark Thy",
        "Vesterhavet og badestrande",
        "Limfjorden og skibsfart",
        "Storebælt og Lillebælt",
        "Øresund og fiskeriet",
        "Yding Skovhøj og Møllehøj",
        "Præstø Fjord",
        "Silkeborgsøerne og Hjejlen",
        "Suså og kanosejlads",
        "Skjern Å og genopretningen",
        "Vejle Ådal",
        "Rebild Bakker og Rebildfesten",
        "Dyrehaven nord for København",
        "Bregentved og de sjællandske herregårde",
        "Halsnæs og Frederiksværk",
        "Furesøen",
        "Arresø som Danmarks største sø",
    ],

    # ── Science & tech ─────────────────────────────────────────────────────
    "science": [
        "H.C. Ørsted og opdagelsen af elektromagnetismen 1820",
        "Niels Bohr og atomteorien",
        "Niels Bohr og Nobelprisen 1922",
        "Niels Bohrs institut på Blegdamsvej",
        "Tycho Brahe og observatoriet Uraniborg på Hven",
        "Ole Rømer og lysets hastighed",
        "August Krogh og Nobelprisen 1920",
        "Niels Ryberg Finsen og lysbehandling",
        "Johannes Fibiger og kræftforskning",
        "Henrik Dam og K-vitamin",
        "Jens Christian Skou og Nobelprisen i kemi 1997",
        "Ben Roy Mottelson og Aage Bohr og Nobelprisen 1975",
        "Willem de Sitter og Bohr-Sommerfeld-teorien",
        "Novo Nordisk og insulinproduktion",
        "Lundbeck og psykiatrisk medicin",
        "Coloplast og hospitalsudstyr",
        "Vestas og vindmøller",
        "Ørsted og havvindmølleparker",
        "COWI og ingeniørrådgivning",
        "Rambøll og infrastrukturprojekter",
        "Bang & Olufsen og designfilosofi",
        "Danske forskningsbidrag til CERN",
        "DTU Fysik og materialeforskning",
        "Aarhus Universitets astrofysiske forskning",
    ],

    # ── Sports ─────────────────────────────────────────────────────────────
    "sports": [
        "Håndboldherrelandsholdets EM-guld 2008",
        "Håndboldherrelandsholdets VM-guld 2019 og 2021 og 2023",
        "Nikolaj Jacobsen som håndboldlandstræner",
        "Mikkel Hansen og hans karriere",
        "Kvindehåndboldlandsholdets OL-guld 1996",
        "Anja Andersen og håndboldhistorien",
        "Fodboldlandsholdets EM-guld 1992",
        "Peter Schmeichel og hans karriere",
        "Michael Laudrup og Brian Laudrup",
        "Kasper Schmeichel og VM 2018",
        "Christian Eriksen og hans hjertestop ved EM 2021",
        "FC Københavns dominans i Superligaen",
        "AGF Aarhus og hooligankulturen",
        "Brøndby IF og Nis-navnet",
        "Bjarne Riis og Tour de France 1996",
        "Michael Rasmussen og Tour de France 2007",
        "Jakob Fuglsang og hans karriere",
        "Jonas Vingegaard og Tour de France 2022 og 2023",
        "Mads Pedersen og VM i cykling 2019",
        "Wilfred Buchholtz og roning",
        "Caroline Wozniacki og tennis",
        "Mikkel Kessler og boksning",
        "Nicki Pedersen og speedway",
        "Tom Kristensen og Le Mans-sejrene",
        "Lasse Norman Hansen og banecykling",
        "Viktor Axelsen og badminton",
        "Peter Gade og badminton",
    ],

    # ── Art & architecture ─────────────────────────────────────────────────
    "art_architecture": [
        "Skagensmalerne P.S. Krøyer, Anna Ancher, Michael Ancher",
        "Vilhelm Hammershøis interiør-malerier",
        "L.A. Ring og landsbyfolk-motiver",
        "C.W. Eckersberg og den danske guldalder",
        "Christen Købke og guldalder-landskaber",
        "Bertel Thorvaldsens skulpturer",
        "Thorvaldsens Museum",
        "Bjørn Wiinblads keramik og illustrationer",
        "Arne Jacobsens Æg-stol og Svanen",
        "Arne Jacobsen og SAS Royal Hotel",
        "Poul Henningsen og PH-lampen",
        "Verner Panton og S-stolen",
        "Hans J. Wegner og Y-stolen",
        "Finn Juhl og møbeldesign",
        "Kaare Klint og møbelskolen",
        "Nanna Ditzel og møbeldesign",
        "Louis Poulsen og designbelysning",
        "Bang & Olufsens Beolab-højtalere",
        "Bjarke Ingels og BIG-arkitekterne",
        "Jørn Utzon og operahuset i Sydney",
        "Jørn Utzon og Bagsværd Kirke",
        "Henning Larsen og operaen i København",
        "Louisiana Museum for Moderne Kunst",
        "ARoS Aarhus Kunstmuseum og Regnbuepanoramaet",
        "Statens Museum for Kunst",
        "Ny Carlsberg Glyptotek",
        "Georg Jensens sølvsmedje",
        "Royal Copenhagen porcelæn",
        "Holmegaard glasværker",
        "Kay Bojesen og aben i træ",
    ],

    # ── Food & drink ───────────────────────────────────────────────────────
    "food_drink": [
        "Stegt flæsk med persillesovs som nationalret",
        "Smørrebrød med sild og æg",
        "Frikadeller og pommes frites",
        "Æbleflæsk fra Fyn",
        "Medisterpølse til julefrokosten",
        "Grønlangkål og hamburgerryg",
        "Andesteg med rødkål 1. juledag",
        "Risalamande med mandelgave",
        "Rødgrød med fløde og udtale-udfordringen",
        "Wienerbrød og danish pastry-arv",
        "Rugbrød og danskernes forbrug",
        "Fastelavnsboller med creme",
        "Kanelsnegle og bagværk",
        "Æbleskiver med sukker",
        "Klejner til jul",
        "Brune kager og pebernødder",
        "Karrysild til påsken",
        "Marinerede sild til frokost",
        "Fiskefilet med remoulade og citron",
        "Leverpostej med bacon og champignon",
        "Hakkebøf med bløde løg og spejlæg",
        "Boller i karry",
        "Mørbradbøf med bløde løg",
        "Krebinetter",
        "Flæskesteg med sprøde svær",
        "Røget makrel fra Bornholm",
        "Rygeost fra Fyn",
        "Havarti-ost",
        "Danablu blåskimmelost",
        "Vesterhavsost",
        "René Redzepi og Noma-restauranten",
        "Ny nordisk mad-manifestet",
        "Kanelsnegle og fastelavnsboller",
        "Sole meunière på København",
        "Julefrokosttraditionen",
        "Snapsvise-traditionen",
        "Snapse og krydderaquavit",
        "Elephant Beer og Tuborg",
        "Carlsberg og J.C. Jacobsen",
        "Mikkeller-håndværksøl",
        "Danske vine fra Djursland",
        "Kolonihaveforeningens grill-tradition",
    ],

    # ── Everyday life & culture ────────────────────────────────────────────
    "everyday_culture": [
        "Hyggens rolle i danskernes selvforståelse",
        "Cykelkulturen i København",
        "Cykelstisystemet i Danmark",
        "Danskernes tillid til hinanden ('social kapital')",
        "Kolonihaverne og deres regler",
        "Sommerhusreglen for udlændinge",
        "Skøn og fornuft i dansk hverdagsliv",
        "Jantelovens indflydelse",
        "Konfirmationens rolle for teenagere",
        "Studenterkørslen efter eksamen",
        "Sankt Hans-aften og bålet på stranden",
        "Fastelavnstønden og udklædning",
        "Grundlovsdag 5. juni",
        "Store bededag som ophævet helligdag 2024",
        "Kongens fødselsdag som flag-dag",
        "Efterårsferien uge 42",
        "Vinterferien uge 7",
        "Sommerhus-traditionen",
        "Kolonihave-kulturen",
        "Cykel-i-arbejde-kulturen",
        "Danskernes forbrug af kaffe",
        "Wienerbrød til morgenkaffen",
        "Frokostpakke og madpakke",
        "Kantiner på arbejdspladser",
        "Fredagsbar-kulturen",
        "Julekalendere på DR og TV 2",
        "Nissen på loftet i julen",
        "Julekransen og adventslys",
        "Julehilsen og nytårshilsen",
        "Skoletraditioner: 9. og 10. klasse",
        "Efterskoleordningen",
        "Højskoler og folkeoplysning",
        "SU-systemet",
        "Boligstøtten og børnepenge",
        "Barsel og forældreorlov",
        "Ferieloven og feriedage",
    ],

    # ── Media & press ──────────────────────────────────────────────────────
    "media": [
        "Politiken og dagbladet",
        "Berlingske og dets historie",
        "Jyllands-Posten og Muhammed-tegningerne",
        "Ekstra Bladets tabloid-stil",
        "BT som avis",
        "Weekendavisen og Bo Lidegaard",
        "Kristeligt Dagblad",
        "Information og Politikens Hus",
        "TV 2 og etableringen 1988",
        "DR og public service",
        "DR2 og kulturprogrammerne",
        "DRK og børnekanalen",
        "Radio24syv (nedlagt 2019)",
        "Danmarks Radios koncertsal",
        "Symfoniorkestret og Copenhagen Phil",
    ],

    # ── Companies & brands ─────────────────────────────────────────────────
    "companies": [
        "Novo Nordisk og GLP-1-medicin (Ozempic, Wegovy)",
        "Mærsk og global containershipping",
        "Grundfos og pumper",
        "LEGO og Ole Kirk Christiansen",
        "LEGO og Billund som hovedsæde",
        "LEGO Star Wars og filmene",
        "Danfoss og termostater",
        "Chr. Hansen og bakteriekulturer",
        "H+H Fondens boligbyggeri",
        "ISS Facility Services",
        "DSV og logistik",
        "Vestas og vindmøller",
        "Ørsted og grøn energi",
        "TDC og telekom",
        "Nordea og bankvæsen",
        "Danske Bank og hvidvasksagen",
        "Jyske Bank og lokal forankring",
        "COOP og brugsforeninger",
        "Salling Group (Netto, Bilka, Føtex)",
        "Ecco og sko",
        "Bestseller (Jack & Jones, Vero Moda)",
        "PANDORA og smykker",
        "Georg Jensen og sølv",
        "Rockwool og isolering",
        "Grundfos og pumper",
        "Trelleborg og gummi",
        "Novozymes og enzymer",
    ],

    # ── Holidays & traditions ──────────────────────────────────────────────
    "holidays": [
        "Julefrokosttraditionen",
        "Nytår og fyrværkeri",
        "Nytårstalen fra Dronningen og Statsministeren",
        "Fastelavn og slå katten af tønden",
        "Påsken og påskefrokosten",
        "Store bededag (nu ophævet)",
        "Kristi himmelfartsdag",
        "Pinsen",
        "Sankt Hans-aften og heksen på bålet",
        "Grundlovsdag 5. juni",
        "Mortens Aften 10. november",
        "1. søndag i advent",
        "Lucia-optog 13. december",
        "Juleaften 24. december og gaverne",
        "Andre juledag",
        "Danneborg-flagning på fødselsdage",
        "Røde løber-billeder ved statsbesøg",
        "10-års-jubilæum for boliger",
        "Bryllupstraditionen: rispose og bilkonvoj",
        "Barnedåb i folkekirken",
        "Konfirmationsbrunch",
        "Studenterhue og karamelfeje",
    ],

    # ── Grønland & Færøerne ────────────────────────────────────────────────
    "greenland_faroes": [
        "Grønlands hjemmestyre 1979",
        "Grønlands selvstyre 2009",
        "Nuuk som Grønlands hovedstad",
        "Ilulissat Isfjord som verdensarv",
        "Kalaallisut som officielt sprog",
        "Fiskeriets betydning for Grønland",
        "Færøernes hjemmestyre 1948",
        "Tórshavn som Færøernes hovedstad",
        "Færøernes sprog og litteratur",
        "William Heinesens forfatterskab",
        "Færøsk hvalfangst-tradition",
        "Nordatlantens Brygge i København",
        "Færøernes fisketank-eksport",
        "Grønlands isafsmeltning og klima",
        "Thulesagen og Ivalu",
    ],

    # ── Language & linguistics ─────────────────────────────────────────────
    "language": [
        "Retskrivningsordbogen og Dansk Sprognævn",
        "Rødgrød med fløde-udtale-testen",
        "De 29 bogstaver i det danske alfabet",
        "Bogstaverne æ, ø, å",
        "Stød i danske ord",
        "Jysk dialekt",
        "Fynsk dialekt",
        "Bornholmsk dialekt",
        "Sønderjysk dialekt",
        "Rigsdansk som standardsprog",
        "Danske låneord fra engelsk",
        "Franske låneord i det 1700-tal danske",
        "Ludvig Holberg og modersmålsdiskussionen",
        "Grimm-loven og danske konsonanter",
        "Ordklassernes brug i dansk",
        "Nutids-r i verber",
        "Kongeriget Danmarks navn",
        "Dannebrog og legenden om himlen 1219",
    ],

    # ── Nature & climate ───────────────────────────────────────────────────
    "climate": [
        "Danmarks vindenergiproduktion",
        "Klima-mål: CO2-reduktion 70% inden 2030",
        "Vandkraftværket ved Tange",
        "Vadehavets tidevand",
        "Danmark uden bjerge over 200 m",
        "Nordsøens fiskebestand",
        "Østersøens iltsvind",
        "Danmarks skovarealer",
        "Miljøbeskyttelsesloven",
        "Sortkrudt-forbud og fyrværkeri",
        "Havneenergien i Esbjerg og Aalborg",
        "Havvindmølleparken Horns Rev",
        "Anholt Havmøllepark",
        "Kriegers Flak Havmøllepark",
        "Biogas fra landbruget",
        "Cirkulær økonomi i danske virksomheder",
    ],

    # ── Education ──────────────────────────────────────────────────────────
    "education": [
        "Folkeskolens grundskoleforløb 0.-9. klasse",
        "9. klasses afgangseksamen",
        "Gymnasieformen STX",
        "HHX handelsgymnasiet",
        "HTX teknisk gymnasium",
        "HF som 2-årig ungdomsuddannelse",
        "Erhvervsuddannelser og lærlingesystemet",
        "Efterskoler som 8.-10. klasse-alternativ",
        "Højskoler for voksne",
        "SU og støttebeløb",
        "Optagelse på universiteterne (kvote 1 og 2)",
        "Københavns Universitet grundlagt 1479",
        "Aarhus Universitet grundlagt 1928",
        "Danmarks Tekniske Universitet",
        "Syddansk Universitet",
        "Aalborg Universitets problembaserede læring",
        "Copenhagen Business School",
        "IT-Universitetet i København",
        "Roskilde Universitets projektarbejde",
        "Danmarks Pædagogiske Universitet",
    ],

    # ── Vikings & religion ─────────────────────────────────────────────────
    "religion": [
        "Folkekirken og medlemskabet",
        "Kirkeskatten og kirkens økonomi",
        "Grundtvig-Kolds skolebevægelse",
        "Indre Mission",
        "Tidehverv-teologien",
        "K.E. Løgstrup og etisk tænkning",
        "Kristendom mod islam-debatten",
        "Frikirker i Danmark",
        "Katolske kirker efter reformationen",
        "Baptister og pinsemenigheder",
        "Muslimsk gravplads i Brøndby",
        "Jødisk menighed i København",
        "Jødernes flugt til Sverige 1943",
        "Buddhisme og hinduisme i det multikulturelle Danmark",
    ],

    # ── EU & international ─────────────────────────────────────────────────
    "eu_international": [
        "Danmarks EF-medlemskab fra 1973",
        "Danmarks EU-forbehold",
        "Retsforbeholdet og Europol-afstemningen 2015",
        "Eurofobolkeafstemning 2000",
        "Nordisk Råd og de nordiske lande",
        "Nordisk Ministerråd",
        "Færøernes forhold til EU",
        "Grønlands udtræden af EF 1985",
        "Danmark og NATO siden 1949",
        "Danske soldater i Afghanistan",
        "Danske soldater i Irak",
        "Ukraine-krigen og Danmarks våbenstøtte",
        "Anders Fogh Rasmussen som NATO-generalsekretær",
        "Danmarks bilaterale forhold til Tyskland",
        "Danmark-Sverige-Norge samarbejdet",
        "Danske missioner i Afrika",
    ],
}


# Flatten for uniform sampling
TOPICS_FLAT: list[tuple[str, str]] = [
    (subject, topic) for subject, topics in TOPICS.items() for topic in topics
]


def sample_topic(rng) -> tuple[str, str]:
    """Sample (subject, topic). Uniform across ALL topics, not per-subject."""
    return rng.choice(TOPICS_FLAT)


def summary() -> dict:
    """Debug: subject counts."""
    return {s: len(v) for s, v in TOPICS.items()} | {"_total": len(TOPICS_FLAT)}


if __name__ == "__main__":
    import json, sys
    print(json.dumps(summary(), ensure_ascii=False, indent=2), file=sys.stderr)
