"""Read the ORIGINAL Team-ACE/ToolACE and emit the shape our pipeline expects.

WHY NOT THE TOOLMIND COPY. `Nanbeige/ToolMind` ships a normalised ToolACE, and
we already ran the pipeline on it -- but every ToolMind file has had its
ASSISTANT turns regenerated by a reasoning model: 100% of rows in all seven
open_datasets files carry `<think>`, always in the assistant turn, and the
calls are restructured into `tool_calls`. The user turns, the tool schemas and
the executed tool results are the source's; the assistant behaviour is not.

    ORIGINAL   {"from": "assistant", "value": "[Get Available OCR Algorithms()]"}
    TOOLMIND   {"role": "assistant", "tool_calls": [...], "content": " "}  + <think>

So if the point is to train on something other than a model's guess at which
tool to call, the original is the thing to read.

WHAT THE ORIGINAL LOOKS LIKE

  system         prose, ending "...invoke:\\n[ {tool}, {tool}, ... ]"
  conversations  [{"from": "user"|"assistant"|"tool", "value": ...}]
  a call turn    [Market Trends API(trend_type="MARKET_INDEXES", country="us")]
  a text turn    ordinary prose, no brackets
  a tool turn    [{"name": ..., "results": {...}}]

THE CALL SYNTAX IS THE WORK. It is Python-ish but not Python: names carry
spaces and slashes (`Market Trends API`, `/madlibs-diceware`), so the name
cannot be tokenised as an identifier; several calls may sit in one bracket
(parallel calling, which glaive never does); and string values contain commas
and parentheses that must not be split on. Hence a depth-aware scanner rather
than a regex, and `ast.literal_eval` for the values once they are isolated.

    uv run python scripts/parse_toolace_original.py --out scratch/toolace_orig.jsonl
    uv run python scripts/parse_toolace_original.py --check      # controls only
"""
from __future__ import annotations

import argparse
import ast
import json
import re
from pathlib import Path

REPO = "Team-ACE/ToolACE"
FILE = "data.json"
MARKER = "Here is a list of functions in JSON format that you can invoke"


def split_top_level(s: str, sep: str = ",") -> list[str]:
    """Split on `sep` at bracket depth 0, respecting quotes.

    `Text Analysis(text="excellent, but the wait was long")` must not split on
    the comma inside the string, and `f(a=[1,2], b=3)` must not split inside
    the list.
    """
    out, buf, depth, quote, esc = [], [], 0, None, False
    for ch in s:
        if esc:
            buf.append(ch); esc = False; continue
        if ch == "\\" and quote:
            buf.append(ch); esc = True; continue
        if quote:
            buf.append(ch)
            if ch == quote:
                quote = None
            continue
        # A quote only OPENS a string where a value can start -- after `=`,
        # `,`, `(` or `[`. Tool names carry apostrophes (`Trip's Current
        # Status`, `Get Today's Word`), and treating those as string openers
        # swallowed the comma between two calls, merging them into one and
        # corrupting the name. 21 of 18,097 calls.
        if ch == '"' or (ch == "'" and (not buf or
                                        (buf[-1].strip() or ",") in "=,([")):
            quote = ch; buf.append(ch); continue
        if ch in "([{":
            depth += 1
        elif ch in ")]}":
            depth -= 1
        if ch == sep and depth == 0:
            out.append("".join(buf)); buf = []
            continue
        buf.append(ch)
    if "".join(buf).strip():
        out.append("".join(buf))
    return [x.strip() for x in out if x.strip()]


def parse_value(raw: str):
    """A call argument's value. Python literals, with JSON spellings allowed."""
    raw = raw.strip()
    try:
        return ast.literal_eval(raw)
    except Exception:
        pass
    for a, b in (("true", "True"), ("false", "False"), ("null", "None")):
        if raw == a:
            return ast.literal_eval(b)
    try:
        return json.loads(raw)
    except Exception:
        return raw.strip("\"'")          # last resort: the bare text


def parse_calls(value: str):
    """`[Name(k=v, ...), Other(...)]` -> [{"function": {...}}], or None.

    None means "this assistant turn is prose, not a call" -- the distinction
    matters because ToolACE mixes them freely, including refusals like
    "I don't have the capability to..." which must NOT become a call.
    """
    s = (value or "").strip()
    if not (s.startswith("[") and s.endswith("]")):
        return None
    inner = s[1:-1].strip()
    if not inner:
        return None
    calls = []
    for part in split_top_level(inner):
        if not part.endswith(")"):
            return None
        # The name is everything before the LAST top-level "(" -- not the
        # first. Tool names contain parentheses: `Daily Forecast (10 days)`,
        # `Countries All (min)`, `Sending SMS OTP (Custom OTP - Custom
        # Template)`. Splitting on the first one truncated 98 of 18,080 calls
        # to a name no catalogue contains, silently corrupting the single
        # field everything downstream keys on.
        depth = 0; op = -1
        for i, ch in enumerate(part):
            if ch == "(":
                if depth == 0:
                    op = i
                depth += 1
            elif ch == ")":
                depth -= 1
        if op <= 0:
            return None
        name = part[:op].strip()
        # A call turn names a FUNCTION; a tool-result turn is a JSON array of
        # objects and would arrive here as `{...}` with no name.
        if not name or name.startswith(("{", "\"", "'")):
            return None
        args = {}
        for kv in split_top_level(part[op + 1:-1]):
            eq = kv.find("=")
            if eq <= 0:
                return None
            args[kv[:eq].strip()] = parse_value(kv[eq + 1:])
        calls.append({"function": {"name": name, "arguments": args}})
    return calls or None


def parse_tools(system: str):
    """The JSON array the system prompt ends with, normalised to our wrapper."""
    i = system.find(MARKER)
    if i < 0:
        return []
    tail = system[i + len(MARKER):]
    j = tail.find("[")
    if j < 0:
        return []
    try:
        arr, _ = json.JSONDecoder().raw_decode(tail[j:])
    except Exception:
        return []
    out = []
    for t in arr:
        if not isinstance(t, dict) or not t.get("name"):
            continue
        fn = {"name": t["name"], "description": t.get("description", "")}
        params = t.get("parameters") or {}
        if isinstance(params, dict):
            params = dict(params)
            # ToolACE writes `"type": "dict"`; every other source and our own
            # renderer say "object".
            if params.get("type") == "dict":
                params["type"] = "object"
            for k, v in list((params.get("properties") or {}).items()):
                if isinstance(v, dict) and v.get("type") == "dict":
                    v["type"] = "object"
        fn["parameters"] = params
        # A stray function-level `"required": null` sits beside `parameters`
        # in the source; the real one is inside `parameters`. Dropping the
        # null avoids two places disagreeing about the same thing.
        if t.get("required"):
            fn["required"] = t["required"]
        out.append({"type": "function", "function": fn})
    return out


# --- flattened-dialogue recovery ---------------------------------------------
#
# 15% of rows carry a whole multi-turn conversation SERIALISED into one user
# turn, wrapped in generation scaffolding:
#
#     Role definition:
#      Inquirer: A user who raises an inquiry.
#      Response assistant: Communicates with the inquirer and provides ...
#
#      Historical dialog data is as follows:
#     Inquirer: Can you check the results of our campaign last week?
#     Response assistant: Could you please provide the ID of the campaign?
#     Inquirer: The campaign ID is 12345.
#
#      Please continue your answer given the historical dialog. Your role is
#      the Response assistant.
#
# Stripping the wrapper would throw the conversation away. Parsing it back
# into turns recovers two things the corpus is short of: genuine multi-turn
# structure (4.7% of the training mix, and all of it from one source), and the
# assistant ASKING FOR A MISSING REQUIRED ARGUMENT -- "Could you please
# provide the ID" -- which no abstention row teaches.
HEADER = re.compile(r"^\s*Role definition:.*?Historical dialog data is as follows:\s*",
                    re.S | re.I)
FOOTER = re.compile(r"\s*Please continue your answer given the historical dialog\.?"
                    r".*$", re.S | re.I)
TURN = re.compile(r"^(Inquirer|Response assistant)\s*:\s*(.*)$", re.I)


def recover_dialogue(text: str):
    """Flattened transcript -> [{role, content}], or None if not scaffolded."""
    if not isinstance(text, str) or not HEADER.search(text):
        return None
    body = FOOTER.sub("", HEADER.sub("", text)).strip()
    if not body:
        return None
    turns, role, buf = [], None, []
    for line in body.splitlines():
        m = TURN.match(line.strip())
        if m:
            if role and "".join(buf).strip():
                turns.append({"role": role, "content": "\n".join(buf).strip()})
            role = "user" if m.group(1).lower() == "inquirer" else "assistant"
            buf = [m.group(2)]
        elif role:
            buf.append(line)          # continuation of the current speaker
    if role and "".join(buf).strip():
        turns.append({"role": role, "content": "\n".join(buf).strip()})
    # The transcript is context for what the assistant says NEXT, so it must
    # end on the user. A trailing assistant line would put two assistant turns
    # back to back once the real reply is appended.
    while turns and turns[-1]["role"] == "assistant":
        turns.pop()
    return turns or None


# --- source corruption -------------------------------------------------------
#
# ToolACE has had a type-name substitution applied to its IDENTIFIERS, so
# `date` (and `file`, and the `date` inside `validate`) became `string`:
#
#     start_string  end_string  string_range  departure_string   <- *_date
#     valistring    Valistring Phone                             <- validate
#     prostring_id                                               <- profile_id
#
# 6.5% of rows carry one. The damage is in the identifier, which is exactly
# what the model leans on hardest -- grounding scores 49.3% when a field name
# is unseen against 88-96% when familiar -- and it propagates through
# translation into the user-facing text: `Get Baseball Schedule(string=...)`
# became "på strengen 'Mandag'", i.e. "on the string 'Monday'".
#
# Dropped rather than repaired: reversing the substitution means guessing
# which `string` was a `date`, and at 10,534 rows we can afford to lose them.
# A few legitimate `query_string`-style params go too; that is the trade.
CORRUPT = re.compile(r"valistring|prostring|(^|_)string(_|$)", re.I)
# An unfilled generation placeholder the author never substituted.
PLACEHOLDER = re.compile(r"\[(insert|your|indsæt)[^\]]{0,40}\]", re.I)


def corruption(row: dict) -> str | None:
    """Why this row should be dropped, or None. Checked on the CONVERTED row."""
    for t in row["tools"]:
        fn = t.get("function", t)
        if CORRUPT.search(str(fn.get("name") or "")):
            return "corrupt-tool-name"
        for k in ((fn.get("parameters") or {}).get("properties") or {}):
            if CORRUPT.search(k):
                return "corrupt-param-name"
    for t in row["conversations"]:
        if t.get("role") == "user" and PLACEHOLDER.search(str(t.get("content") or "")):
            return "unfilled-placeholder"
        for c in (t.get("tool_calls") or []):
            for k in (c["function"].get("arguments") or {}):
                if CORRUPT.search(str(k)):
                    return "corrupt-arg-name"
    return None


def unwrap_result(val):
    """ToolACE's `[{"name": ..., "results": R}]` -> the bare object the rest of
    the pipeline reads. Returns None if the row should be dropped.

    THE CONTRACT. Every other source hands a tool turn a bare JSON object:

        glaive   {"converted_amount": 425.50, "from_currency": "USD"}
        ToolACE  [{"name": "fetchData", "results": {"data": "..."}}]

    Unwrapped here rather than downstream, because `inject_distractors` and
    `gen_tool_answer_turns` both do `json.loads` then `isinstance(dict)` and
    would silently skip every ToolACE row as `payload-not-object`.

    MULTI-RESULT TURNS ARE DROPPED. 28 of 1,129 turns carry one result per
    parallel call. The array order matches the call order -- that was
    checked, zero mismatches -- but our stages pair a result with the NEAREST
    PRECEDING tool_call, so three results after three calls would associate
    result[0] with call[2]. Emitting them would ship a silent mis-pairing;
    2.5% is cheap to lose instead.
    """
    if isinstance(val, str):
        try:
            val = json.loads(val)
        except Exception:
            return None
    if isinstance(val, dict):
        return json.dumps(val, ensure_ascii=False)      # already the contract
    if not isinstance(val, list) or len(val) != 1:
        return None
    e = val[0]
    if not isinstance(e, dict) or "results" not in e:
        return None
    res = e["results"]
    # A list or bare string result is still a payload; name it so the object
    # contract holds. `result` is a field name the corpus already contains,
    # so this introduces no unfamiliar key.
    if not isinstance(res, dict):
        res = {"result": res}
    return json.dumps(res, ensure_ascii=False)


def convert(row: dict):
    tools = parse_tools(row.get("system") or "")
    convs = []
    for t in row.get("conversations") or []:
        role = t.get("from")
        val = t.get("value")
        if role == "user":
            rec = recover_dialogue(val)
            if rec:
                convs.extend(rec)
            else:
                convs.append({"role": "user", "content": val})
        elif role == "tool":
            payload = unwrap_result(val)
            if payload is None:
                return None            # shape we cannot hand to the pipeline
            convs.append({"role": "tool", "content": payload})
        elif role == "assistant":
            calls = parse_calls(val if isinstance(val, str) else "")
            if calls:
                convs.append({"role": "assistant", "content": "",
                              "tool_calls": calls})
            else:
                convs.append({"role": "assistant", "content": val})
        else:
            return None                   # unknown role: drop rather than guess
    if not convs or not tools:
        return None
    return {"tools": tools, "conversations": convs}


# --- planted controls --------------------------------------------------------
CALL_CASES = [
    ('[GetCompetitions()]', [("GetCompetitions", {})]),
    ('[Market Trends API(trend_type="MARKET_INDEXES", country="us")]',
     [("Market Trends API", {"trend_type": "MARKET_INDEXES", "country": "us"})]),
    ('[/madlibs-diceware(nphrase=2)]', [("/madlibs-diceware", {"nphrase": 2})]),
    # a string containing a comma AND a full stop -- the split must respect quotes
    ('[Text Analysis(text="The service was excellent, but the wait was long.")]',
     [("Text Analysis", {"text": "The service was excellent, but the wait was long."})]),
    # parallel calls in one bracket: glaive never does this, ToolACE does
    ('[A(x=1), B Name(y="z")]', [("A", {"x": 1}), ("B Name", {"y": "z"})]),
    ('[f(flag=true, none=null, xs=[1, 2])]',
     [("f", {"flag": True, "none": None, "xs": [1, 2]})]),
    # nested parens inside a quoted value
    ('[g(q="what (really) happened, then?")]',
     [("g", {"q": "what (really) happened, then?"})]),
    # tool names that CONTAIN parentheses -- the bug this control exists for
    ('[Daily Forecast (10 days)(days=3)]',
     [("Daily Forecast (10 days)", {"days": 3})]),
    ('[Countries All (min)()]', [("Countries All (min)", {})]),
    ('[Sending SMS OTP (Custom OTP - Custom Template)(to="45")]',
     [("Sending SMS OTP (Custom OTP - Custom Template)", {"to": "45"})]),
    # apostrophes in NAMES must not open a string, or the comma between two
    # calls is invisible and they merge
    ('[Get Today\'s Word(difficulty="hard"), Other(x=1)]',
     [("Get Today's Word", {"difficulty": "hard"}), ("Other", {"x": 1})]),
    ("[Trip's Current Status(id=123), Trip's Current Status(id=124)]",
     [("Trip's Current Status", {"id": 123}), ("Trip's Current Status", {"id": 124})]),
    # ...but a single-quoted VALUE still parses
    ("[f(a='x, y', b=2)]", [("f", {"a": "x, y", "b": 2})]),
]
NOT_CALLS = [
    "I don't have the capability to directly fetch real-time trends.",
    "",
    "[]",
    '[{"name": "X", "results": {"a": 1}}]',      # a tool-result turn
    "Here are the top Market Trends in the US right now:",
]


SCAFFOLDED = (
    "Role definition:\n Inquirer: A user who raises an inquiry.\n"
    " Response assistant: Communicates with the inquirer and provides answers.\n\n"
    " Historical dialog data is as follows:\n"
    "Inquirer: Can you check the campaign results?\n"
    "Response assistant: Could you please provide the campaign ID?\n"
    "Inquirer: The campaign ID is 12345.\n\n"
    " Please continue your answer given the historical dialog. Your role is the"
    " Response assistant.\n")


def check():
    for raw, want in CALL_CASES:
        got = parse_calls(raw)
        assert got is not None, f"parsed as prose: {raw}"
        pairs = [(c["function"]["name"], c["function"]["arguments"]) for c in got]
        assert pairs == want, f"{raw}\n  got  {pairs}\n  want {want}"
    for raw in NOT_CALLS:
        got = parse_calls(raw)
        assert got is None, f"prose parsed as a call: {raw!r} -> {got}"
    sys_ = ('...invoke:\n[{"name": "f", "description": "d", "parameters": '
            '{"type": "dict", "properties": {"a": {"type": "dict"}}, '
            '"required": ["a"]}, "required": null}]')
    tools = parse_tools(MARKER.join(["", sys_]))
    assert len(tools) == 1, tools
    fn = tools[0]["function"]
    assert fn["parameters"]["type"] == "object"
    assert fn["parameters"]["properties"]["a"]["type"] == "object"
    assert fn["parameters"]["required"] == ["a"]
    assert "required" not in fn, "stray function-level required:null was kept"
    rec = recover_dialogue(SCAFFOLDED)
    assert rec is not None, "scaffolded transcript not recognised"
    assert [t["role"] for t in rec] == ["user", "assistant", "user"], rec
    assert rec[0]["content"] == "Can you check the campaign results?", rec[0]
    assert rec[1]["content"] == "Could you please provide the campaign ID?", rec[1]
    assert rec[2]["content"] == "The campaign ID is 12345.", rec[2]
    assert "Role definition" not in json.dumps(rec), "header leaked into a turn"
    assert "Please continue" not in json.dumps(rec), "footer leaked into a turn"
    # must end on the user, or the real reply becomes a second assistant turn
    trailing = SCAFFOLDED.replace("Inquirer: The campaign ID is 12345.\n", "")
    r2 = recover_dialogue(trailing)
    assert r2 and r2[-1]["role"] == "user", r2
    # an ordinary user turn is untouched
    assert recover_dialogue("Just find me a restaurant in Aarhus.") is None
    def _row(pname="q", tname="f", user="hi"):
        return {"tools": [{"type": "function", "function": {
                    "name": tname, "description": "",
                    "parameters": {"type": "object", "properties": {pname: {}}}}}],
                "conversations": [{"role": "user", "content": user}]}
    assert corruption(_row(pname="start_string")) == "corrupt-param-name"
    assert corruption(_row(pname="string")) == "corrupt-param-name"
    assert corruption(_row(tname="/email/valistring")) == "corrupt-tool-name"
    assert corruption(_row(tname="prostring_lookup")) == "corrupt-tool-name"
    assert corruption(_row(user="here: [indsæt Instagram video URL]")) == "unfilled-placeholder"
    assert corruption(_row(pname="start_date", tname="get_schedule")) is None
    assert corruption(_row(pname="query", user="find me a cafe")) is None
    assert json.loads(unwrap_result('[{"name":"f","results":{"a":1}}]')) == {"a": 1}
    assert json.loads(unwrap_result([{"name":"f","results":{"a":1}}])) == {"a": 1}
    assert json.loads(unwrap_result('{"a":1}')) == {"a": 1}          # already bare
    assert json.loads(unwrap_result('[{"name":"f","results":[1,2]}]')) == {"result": [1, 2]}
    assert json.loads(unwrap_result('[{"name":"f","results":"ok"}]')) == {"result": "ok"}
    assert unwrap_result('[{"name":"a","results":{}},{"name":"b","results":{}}]') is None
    assert unwrap_result("not json at all") is None
    print(f"parse: {len(CALL_CASES)} call shapes, {len(NOT_CALLS)} non-calls, "
          f"tool normalisation, dialogue recovery, corruption filter, result unwrap -- all pass", flush=True)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", type=Path)
    ap.add_argument("--n", type=int, default=0, help="stop after N rows")
    ap.add_argument("--keep-corrupt", action="store_true",
                    help="keep rows carrying the date->string substitution")
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args()
    check()
    if args.check and not args.out:
        return
    from huggingface_hub import hf_hub_download
    path = hf_hub_download(REPO, FILE, repo_type="dataset")
    text = Path(path).read_text()
    dec = json.JSONDecoder()
    # SCAN BY INDEX, never by slicing. `s = s[end:]` on a 37MB string once per
    # row is quadratic -- 10,534 rows moved ~190GB and took 15 minutes.
    # raw_decode takes a start offset, so nothing needs copying.
    pos = 0
    n = len(text)
    while pos < n and text[pos].isspace():
        pos += 1
    if pos < n and text[pos] == "[":
        pos += 1
    from collections import Counter
    why = Counter()
    args.out.parent.mkdir(parents=True, exist_ok=True)
    with args.out.open("w") as fh:
        while True:
            while pos < n and (text[pos].isspace() or text[pos] == ","):
                pos += 1
            if pos >= n or text[pos] == "]":
                break
            try:
                row, pos = dec.raw_decode(text, pos)
            except Exception:
                why["undecodable"] += 1
                break
            out = convert(row)
            if out is None:
                why["dropped"] += 1
                continue
            if not args.keep_corrupt:
                bad = corruption(out)
                if bad:
                    why[f"dropped:{bad}"] += 1
                    continue
            why["kept"] += 1
            why["calls"] += sum(1 for t in out["conversations"] if t.get("tool_calls"))
            why["results"] += sum(1 for t in out["conversations"] if t["role"] == "tool")
            fh.write(json.dumps(out, ensure_ascii=False) + "\n")
            if args.n and why["kept"] >= args.n:
                break
    print(f"{dict(why)}")
    print(f"-> {args.out}", flush=True)


if __name__ == "__main__":
    main()
