"""Push a generated GRPO row set (a dir of <split>.jsonl) to the Hub.

Generic on purpose. push_ner_sft_hf.py / push_icl_schema_format_hf.py each
carry a hardcoded card describing their own dataset; reusing them for a
different build would publish a description of the wrong thing. This takes the
splits it finds and writes a short factual card.

Two configs, matching the sibling datasets so loaders behave the same:
  default  messages + meta
  sft      messages only

Usage:
  python scripts/push_grpo_sets_hf.py --data-dir scratch/icl_grpo_v1 \
      --repo jensjepsen/danish-icl-grpo-v1 --kind icl
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path

from datasets import Dataset
from huggingface_hub import HfApi

KIND_BLURB = {
    "icl": (
        "In-context schema/format induction rows, generated by "
        "`scripts/gen_icl_schema_format.py` with `--exclude-src` against the "
        "`danish-icl-schema-format-v3` build, so **no passage here appears in "
        "that dataset's train split or in any of its published eval splits**. "
        "Built for GRPO: the intended policy already fits the v3 train split "
        "(reward ~1.0), which trains recall rather than induction."
    ),
    "ner": (
        "Danish NER rows over DANSK passages, generated by "
        "`scripts/gen_ner_sft.py` with `--exclude-src` against "
        "`danish-ner-sft-v1`, so **no passage here appears in that dataset's "
        "train split**. Built for GRPO: the intended policy already fits the "
        "v1 train split (reward ~1.0)."
    ),
}


def _cfg(cfg: str, base: str, splits) -> str:
    lines = [f"- config_name: {cfg}", "  data_files:"]
    for sp in splits:
        lines += [f"  - split: {sp}", f"    path: {base}/{sp}-*"]
    return "\n".join(lines)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--data-dir", type=Path, required=True)
    ap.add_argument("--repo", required=True)
    ap.add_argument("--kind", choices=sorted(KIND_BLURB), required=True)
    ap.add_argument("--dry-run", action="store_true")
    args = ap.parse_args()

    files = sorted(args.data_dir.glob("*.jsonl"))
    assert files, f"no *.jsonl in {args.data_dir}"
    data = {f.stem: [json.loads(l) for l in f.open() if l.strip()]
            for f in files}
    # train first, then the rest alphabetically -- purely so the card reads well
    splits = (["train"] if "train" in data else []) + \
             sorted(k for k in data if k != "train")

    for sp in splits:
        n = len(data[sp])
        fmts = {r.get("meta", r).get("format") for r in data[sp]}
        print(f"  {sp:<14} n={n:<6} formats={len(fmts - {None})}")
    if args.dry_run:
        print("dry run — nothing uploaded")
        return

    rows_tbl = "\n".join(f"| `{sp}` | {len(data[sp])} |" for sp in splits)
    card = f"""---
language:
- da
license: apache-2.0
tags:
- danish
- grpo
- in-context-learning
configs:
{_cfg("default", "data", splits)}
{_cfg("sft", "sft", splits)}
---

# {args.repo.split('/')[-1]}

{KIND_BLURB[args.kind]}

| split | rows |
|---|---|
{rows_tbl}
"""

    api = HfApi()
    api.create_repo(args.repo, repo_type="dataset", exist_ok=True)
    for cfg, fn in (("default", lambda R: [{"messages": r["messages"],
                                            **r.get("meta", {})} for r in R]),
                    ("sft", lambda R: [{"messages": r["messages"]} for r in R])):
        for sp in splits:
            Dataset.from_list(fn(data[sp])).push_to_hub(
                args.repo, config_name=cfg, split=sp,
                commit_message=f"{cfg}/{sp} ({len(data[sp])} rows)")
            print(f"  pushed {cfg}/{sp} ({len(data[sp])} rows)", flush=True)
    api.upload_file(path_or_fileobj=card.encode(), path_in_repo="README.md",
                    repo_id=args.repo, repo_type="dataset",
                    commit_message="dataset card")
    print(f"-> https://huggingface.co/datasets/{args.repo}")


if __name__ == "__main__":
    main()
